######################################################################
# Automatically generated by qmake (3.0) Thu Dec 26 15:45:37 2013
######################################################################

TEMPLATE = app
TARGET = monitor
INCLUDEPATH += .

# Input
HEADERS += \
    tpool.h \
    mypool.h
SOURCES += \
    tpool.c \
    main.c
